table Date
	lineageTag: ab84af9e-7a0b-4208-918b-6886cfe94ad4

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 49d1e6a2-95a7-4cc6-a522-e1f8c554d297
		summarizeBy: none
		sourceColumn: Date
		sortByColumn: Year

		variation Variation
			isDefault
			relationship: 7c8cc0ce-037a-4a6c-a247-f8f11eafad20
			defaultHierarchy: LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501.'Date Hierarchy'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Integer'
		dataType: int64
		formatString: 0
		lineageTag: 00197968-cf18-478c-8906-4a02e41f5914
		summarizeBy: sum
		sourceColumn: Date Integer

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: eb468cf3-d072-4ff1-896a-045d9d72260f
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Year Default'
		dataType: string
		lineageTag: 903538c1-760d-4f2b-b73e-6fb8f7e7b513
		summarizeBy: none
		sourceColumn: Year Default

		annotation SummarizationSetBy = Automatic

	column YYYY-MM
		dataType: string
		lineageTag: 23a73da0-cbfb-462c-a3d7-e4f83bca134d
		summarizeBy: none
		sourceColumn: YYYY-MM

		annotation SummarizationSetBy = Automatic

	column Month-Year
		dataType: string
		lineageTag: 9188c3ad-0c20-45b5-954b-5c46cbb49810
		summarizeBy: none
		sourceColumn: Month-Year
		sortByColumn: YYYY-MM

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Of Year'
		dataType: int64
		formatString: 0
		lineageTag: ab6757ab-ccb4-4861-ad73-3ae2484dea3e
		summarizeBy: sum
		sourceColumn: Month Of Year

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 74bee468-e048-40e8-b3f3-cd3f25542892
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Month Of Year'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Name Short'
		dataType: string
		lineageTag: 63d0bfd5-1109-4025-91a6-bf7801db2117
		summarizeBy: none
		sourceColumn: Month Name Short
		sortByColumn: 'Month Of Year'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Name Default'
		dataType: string
		lineageTag: 7129a606-965b-4dd3-8275-bb912b551a28
		summarizeBy: none
		sourceColumn: Month Name Default

		annotation SummarizationSetBy = Automatic

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc868933-a3ae-472e-939e-edb8b01a0bc4
		summarizeBy: none
		sourceColumn: Start of Month

		variation Variation
			isDefault
			relationship: b7e0ca7f-726b-441a-962c-456a2d12da43
			defaultHierarchy: LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1eeddb32-638f-44c3-a2a5-ec5d49e12948
		summarizeBy: none
		sourceColumn: End of Month

		variation Variation
			isDefault
			relationship: 19047c80-59bb-4145-865c-ce1f25556e00
			defaultHierarchy: LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Days in Month'
		dataType: int64
		formatString: 0
		lineageTag: 5b00e8ab-d0a9-455c-83fb-3272fca92bdf
		summarizeBy: sum
		sourceColumn: Days in Month

		annotation SummarizationSetBy = Automatic

	column 'ISO Weeknumber'
		dataType: int64
		formatString: 0
		lineageTag: 31567206-c7ac-4227-82d6-e7b6c079d9e9
		summarizeBy: sum
		sourceColumn: ISO Weeknumber

		annotation SummarizationSetBy = Automatic

	column 'ISO Year'
		dataType: int64
		formatString: 0
		lineageTag: d64c3f6a-f2d7-432e-9008-009c406f753f
		summarizeBy: sum
		sourceColumn: ISO Year

		annotation SummarizationSetBy = Automatic

	column 'Start of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 578d7c74-6de5-40d2-b214-43d1aa0290ca
		summarizeBy: none
		sourceColumn: Start of Week

		variation Variation
			isDefault
			relationship: e76db560-6c06-435b-8445-69eb7ad8bb41
			defaultHierarchy: LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Quarter Number'
		dataType: int64
		formatString: 0
		lineageTag: 5c304509-3585-43ff-b31b-9e1a30bcd9fc
		summarizeBy: sum
		sourceColumn: Quarter Number

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 392d0858-426e-45f4-8d95-18394933c2b0
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year-Quarter
		dataType: string
		lineageTag: a5195d1e-dbe1-416f-bf51-94a0e08be7af
		summarizeBy: none
		sourceColumn: Year-Quarter

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: fb339849-be70-4759-aafd-bab557818828
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Day Name Short'
		dataType: string
		lineageTag: a15e3f7b-bfcb-4130-b2a0-221150915fae
		summarizeBy: none
		sourceColumn: Day Name Short
		sortByColumn: 'Day of Week Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Day of Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 49d70ad7-60cd-46f0-9c07-7e152a018e6b
		summarizeBy: sum
		sourceColumn: Day of Month Number

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Number'
		dataType: int64
		formatString: 0
		lineageTag: 679b70b0-e4cf-4d29-a3ab-8de76cf8b9f3
		summarizeBy: sum
		sourceColumn: Day of Week Number

		annotation SummarizationSetBy = Automatic

	column 'Day of Year Number'
		dataType: int64
		formatString: 0
		lineageTag: 6e935495-9a13-4d9a-8704-b31872b1b9de
		summarizeBy: sum
		sourceColumn: Day of Year Number

		annotation SummarizationSetBy = Automatic

	column 'Day Offset'
		dataType: int64
		formatString: 0
		lineageTag: 1b6df2c8-66f0-484b-be8e-890876acfa4d
		summarizeBy: sum
		sourceColumn: Day Offset

		annotation SummarizationSetBy = Automatic

	column 'Week Offset'
		dataType: int64
		formatString: 0
		lineageTag: 280f1ea7-f699-4bbf-ae62-5c2920e7f8d0
		summarizeBy: sum
		sourceColumn: Week Offset

		annotation SummarizationSetBy = Automatic

	column 'Month Offset'
		dataType: int64
		formatString: 0
		lineageTag: fc156280-1595-49ed-bcd0-bb08f93becad
		summarizeBy: sum
		sourceColumn: Month Offset

		annotation SummarizationSetBy = Automatic

	column 'Quarter Offset'
		dataType: int64
		formatString: 0
		lineageTag: da207e5a-1bdf-4385-bfef-ad2dd3fcdc05
		summarizeBy: sum
		sourceColumn: Quarter Offset

		annotation SummarizationSetBy = Automatic

	column 'Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: 21c57615-cf3a-4744-86ed-dc49525221cf
		summarizeBy: sum
		sourceColumn: Year Offset

		annotation SummarizationSetBy = Automatic

	column 'Is Weekend'
		dataType: int64
		formatString: 0
		lineageTag: f0716f99-ccbe-4d72-9fad-b1c2bd3ae487
		summarizeBy: sum
		sourceColumn: Is Weekend

		annotation SummarizationSetBy = Automatic

	column 'Is Weekday'
		dataType: int64
		formatString: 0
		lineageTag: a5af6108-2c88-46a2-873a-9bb2ab1e7c11
		summarizeBy: sum
		sourceColumn: Is Weekday

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source = ```
				let
				    Today = Date.From( DateTime.LocalNow() ),
				    StartDate = #date(2015, 1, 1),
				    EndDate = Date.EndOfYear( Today ),
				    #"List of Dates" = List.Dates( StartDate, Duration.Days( EndDate - StartDate ) +1, #duration( 1, 0, 0, 0 ) ),
				    #"Converted to Table" = Table.FromList( #"List of Dates", Splitter.SplitByNothing(), type table[Date = Date.Type] ),
				    #"Insert Date Integer" = Table.AddColumn(#"Converted to Table", "Date Integer", each Number.From( Date.ToText( [Date], "yyyyMMdd" ) ), Int64.Type ),
				    #"Insert Year" = Table.AddColumn(#"Insert Date Integer", "Year", each Date.Year([Date]), Int64.Type),
				    // Creates a dynamic year value called 'Current' that moves with the current date. Put this value in a slicer and it automatically switches to the Current period.
				    #"Add Year Default" = Table.AddColumn(#"Insert Year", "Year Default", each if Date.Year( Today ) = [Year] then "Current" else Text.From( [Year] ), type text),
				    #"Insert YYYY-MM" = Table.AddColumn(#"Add Year Default", "YYYY-MM", each Date.ToText( [Date], "yyyy-MM"), type text),
				    #"Insert Month-Year" = Table.AddColumn(#"Insert YYYY-MM", "Month-Year", each Date.ToText( [Date], "MMM yyyy"), type text),
				    #"Insert Month Number" = Table.AddColumn(#"Insert Month-Year", "Month Of Year", each Date.Month([Date]), Int64.Type),
				    #"Insert Month Name" = Table.AddColumn(#"Insert Month Number", "Month Name", each Date.MonthName([Date], "EN-us"), type text),
				    #"Insert Month Name Short" = Table.AddColumn(#"Insert Month Name", "Month Name Short", each Date.ToText( [Date] , "MMM", "EN-us" ), type text),
				    // Creates a dynamic year value called 'Current' that moves with the current date. Put this value in a slicer and it automatically switches to the current period.
				    #"Add Month Name Default" = Table.AddColumn(#"Insert Month Name Short", "Month Name Default", each if Date.Month( Today ) = [Month Of Year] then "Current" else [Month Name], type text ),
				    #"Insert Start of Month" = Table.AddColumn(#"Add Month Name Default", "Start of Month", each Date.StartOfMonth([Date]), type date),
				    #"Inserted End of Month" = Table.AddColumn(#"Insert Start of Month", "End of Month", each Date.EndOfMonth( [Date] ), type date),
				    #"Inserted Days in Month" = Table.AddColumn(#"Inserted End of Month", "Days in Month", each Date.DaysInMonth([Date]), Int64.Type),
				    #"Add ISO Week" = Table.AddColumn(#"Inserted Days in Month", "ISO Weeknumber", each let
				   CurrentThursday = Date.AddDays([Date], 3 - Date.DayOfWeek([Date], Day.Monday ) ),
				   YearCurrThursday = Date.Year( CurrentThursday ),
				   FirstThursdayOfYear = Date.AddDays(#date( YearCurrThursday,1,7),- Date.DayOfWeek(#date(YearCurrThursday,1,1), Day.Friday) ),
				   ISO_Week = Duration.Days( CurrentThursday - FirstThursdayOfYear) / 7 + 1
				in ISO_Week, Int64.Type ),
				    #"Add ISO Year" = Table.AddColumn(#"Add ISO Week", "ISO Year", each Date.Year(  Date.AddDays( [Date], 26 - [ISO Weeknumber] ) ), Int64.Type ),
				    #"Insert Start of Week" = Table.AddColumn(#"Add ISO Year", "Start of Week", each Date.StartOfWeek([Date], Day.Monday ), type date),
				    #"Insert Quarter Number" = Table.AddColumn(#"Insert Start of Week", "Quarter Number", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Insert Quarter Number", "Quarter", each "Q" & Text.From( Date.QuarterOfYear([Date]) ), type text ),
				    #"Add Year-Quarter" = Table.AddColumn(#"Added Quarter", "Year-Quarter", each Text.From( Date.Year([Date]) ) & "-Q" & Text.From( Date.QuarterOfYear([Date]) ), type text ),
				    #"Insert Day Name" = Table.AddColumn(#"Add Year-Quarter", "Day Name", each Date.DayOfWeekName([Date], "EN-us" ), type text),
				    #"Insert Day Name Short" = Table.AddColumn( #"Insert Day Name", "Day Name Short", each Date.ToText( [Date], "ddd", "EN-us" ), type text),
				    #"Insert Day of Month Number" = Table.AddColumn(#"Insert Day Name Short", "Day of Month Number", each Date.Day([Date]), Int64.Type),
				    // Day.Monday indicates the week starts on Monday. Change this in case you want the week to start on a different date. 
				    #"Insert Day of Week" = Table.AddColumn(#"Insert Day of Month Number", "Day of Week Number", each Date.DayOfWeek( [Date], Day.Monday ), Int64.Type),
				    #"Insert Day of Year" = Table.AddColumn(#"Insert Day of Week", "Day of Year Number", each Date.DayOfYear( [Date] ), Int64.Type),
				    #"Add Day Offset" = Table.AddColumn(#"Insert Day of Year", "Day Offset", each Number.From( Date.From( Today ) - [Date] ) , Int64.Type ),
				    #"Add Week Offset" = Table.AddColumn(#"Add Day Offset", "Week Offset", each Duration.Days( Date.StartOfWeek( [Date], Day.Monday ) - Date.StartOfWeek( Today, Day.Monday ) ) / 7 , Int64.Type ),
				    #"Add Month Offset" = Table.AddColumn(#"Add Week Offset", "Month Offset", each ( [Year] - Date.Year( Today ) ) * 12 + ( [Month Of Year] - Date.Month( Today ) ), Int64.Type ),
				    #"Add Quarter Offset" = Table.AddColumn(#"Add Month Offset", "Quarter Offset", each ( [Year] - Date.Year(Today) ) * 4 + Date.QuarterOfYear( [Date] ) - Date.QuarterOfYear( Today ), Int64.Type ),
				    #"Add Year Offset" = Table.AddColumn(#"Add Quarter Offset", "Year Offset", each [Year] - Date.Year(Today), Int64.Type ),
				    #"Insert Is Weekend" = Table.AddColumn(#"Add Year Offset", "Is Weekend", each if Date.DayOfWeek( [Date] ) >= 5 then 1 else 0, Int64.Type ),
				    #"Insert Is Weekday" = Table.AddColumn(#"Insert Is Weekend", "Is Weekday", each if Date.DayOfWeek( [Date] ) < 5 then 1 else 0, Int64.Type )
				in
				    #"Insert Is Weekday"
				```

	annotation PBI_ResultType = Table

